
// =====================
// Power Query Parameters
// =====================
let
    // Provide values in Excel -> Data -> Get Data -> Manage Parameters
    SharePointFolders = {"https://YOURTENANT.sharepoint.com/sites/YourSite/Shared Documents/YourFolder/"},
    SourceExcelFiles = null, // optional list of file names to include
    FuzzyMatchThreshold = 92,
    AllowAutoFinalize = true,
    RoleCanonicalSource = null // optional path/file for canonical role names
in
    SharePointFolders

// =====================
// Helper: Get all Excel files from multiple SharePoint folders
// =====================
let GetAllFiles = (folders as list, optional onlyFiles as nullable list) as table =>
    let
        tables = List.Transform(folders, (f) => SharePoint.Files(f, [ApiVersion = 15])),
        combined = Table.Combine(tables),
        filtered = if onlyFiles = null then combined else Table.SelectRows(combined, each List.Contains(onlyFiles, [Name])),
        excelOnly = Table.SelectRows(filtered, each Text.EndsWith(Text.Lower([Name]), ".xlsx") or Text.EndsWith(Text.Lower([Name]), ".xls")),
        addWebUrl = Table.AddColumn(excelOnly, "WebUrl", each [Link], type text),
        meta = Table.SelectColumns(addWebUrl, {"Name","Folder Path","WebUrl","Date created","Date modified","Content"})
    in
        meta
in GetAllFiles

// =====================
// Helper: Identify sheet type by headers
// =====================
let IdentifySheetType = (tbl as table) as text =>
    let cols = Table.ColumnNames(tbl),
        lower = List.Transform(cols, each Text.Lower(_)),
        hasRole = List.ContainsAny(lower, {"role","role name","resource","position"}),
        hasFTE = List.ContainsAny(lower, {"fte","headcount","workload%"}),
        hasRACI = List.ContainsAny(lower, {"r","a","c","i","raci"}),
        hasActivity = List.ContainsAny(lower, {"activity","task","process","function","core function"}),
        hasQuestion = List.ContainsAny(lower, {"question","response","answer"}),
        hasDependency = List.ContainsAny(lower, {"dependency","dependent team","impact"}),
        sheetType = if hasRACI and hasActivity then "RACI" else if hasRole and hasFTE then "Staffing" else if hasQuestion then "Questionnaire" else if hasDependency then "Dependencies" else "Unknown"
    in sheetType
in IdentifySheetType

// =====================
// Function: Load and classify all sheets from a workbook
// =====================
let LoadWorkbookSheets = (binary as binary, sourceFile as text) as table =>
    let
        // Read workbook
        wb = Excel.Workbook(binary, true),
        addSource = Table.AddColumn(wb, "SourceFile", each sourceFile, type text),
        rename = Table.RenameColumns(addSource, {{"Item","SourceSheet"}}),
        keep = Table.SelectColumns(rename, {"SourceSheet","Kind","Data","SourceFile"}),
        // Expand tables only
        onlyTables = Table.SelectRows(keep, each [Kind] = "Sheet" or [Kind] = "Table"),
        // Detect type
        addType = Table.AddColumn(onlyTables, "DetectedType", each @IdentifySheetType([Data])),
        // Add row numbers
        addRow = Table.TransformColumns(addType, {"Data", each Table.AddIndexColumn(_, "SourceRow", 1, 1, Int64.Type)}),
        expanded = Table.ExpandTableColumn(addRow, "Data", Table.ColumnNames(addRow{0}[Data]))
    in
        expanded
in LoadWorkbookSheets

// =====================
// Primary query: Ingest
// =====================
let Ingest =
    let
        files = GetAllFiles(SharePointFolders, SourceExcelFiles),
        addTables = Table.AddColumn(files, "Tables", each LoadWorkbookSheets([Content], [Name])),
        expanded = Table.ExpandTableColumn(addTables, "Tables", {"SourceSheet","Kind","DetectedType","SourceRow"}),
        metadata = Table.SelectColumns(expanded, {"Name","WebUrl","Date created","Date modified"}),
        Metadata = Table.RenameColumns(metadata, {{"Name","SourceFile"},{"Date created","Created"},{"Date modified","Updated"}})
    in
        Metadata
in Ingest

// =====================
// RACI normalization
// =====================
let RACI_Normalized =
    let
        files = GetAllFiles(SharePointFolders, SourceExcelFiles),
        wbTables = Table.AddColumn(files, "Tables", each Excel.Workbook([Content], true)),
        expand = Table.ExpandTableColumn(wbTables, "Tables", {"Item","Kind","Data"}, {"SourceSheet","Kind","Data"}),
        only = Table.SelectRows(expand, each [Kind] = "Sheet" or [Kind] = "Table"),
        // Keep only likely RACI sheets (by headers)
        filtered = Table.SelectRows(only, each @IdentifySheetType([Data]) = "RACI"),
        // Unpivot roles (assume first column is Activity)
        transform = Table.AddColumn(filtered, "Normalized", each let t=[Data] in let
            // Promote headers
            ph = Table.PromoteHeaders(t, [PromoteAllScalars=true]),
            cols = Table.ColumnNames(ph),
            activityCol = cols{0},
            roleCols = List.RemoveFirstN(cols, 1),
            unp = Table.UnpivotOtherColumns(ph, {activityCol}, "RoleSourceName", "Value"),
            trim = Table.TransformColumns(unp, {{activityCol, each Text.Trim(Text.Replace(_, "
", " ")), type text}, {"RoleSourceName", each Text.Trim(_), type text}, {"Value", each Text.Upper(Text.Trim(_)), type text}}),
            // Split multi-letter values (e.g., "R,A,C")
            split = Table.ExpandListColumn(Table.TransformColumns(trim, {"Value", Splitter.SplitTextByAnyDelimiter({",","/"," "}), let each List.Select(_, (x) => x <> "")}), "Value"),
            // Keep only valid RACI letters
            keep = Table.SelectRows(split, each List.Contains({"R","A","C","I"}, [Value])),
            rename=Table.RenameColumns(keep, {{activityCol,"ActivityText"},{"Value","RACI"}})
            in rename),
        expandedNorm = Table.ExpandTableColumn(transform, "Normalized", {"ActivityText","RoleSourceName","RACI"}),
        addSrc = Table.AddColumn(expandedNorm, "SourceFile", each [Name]),
        addRow = Table.AddColumn(addSrc, "SourceRow", each null),
        Master_RACI_Assignments = Table.SelectColumns(addSrc, {"ActivityText","RoleSourceName","RACI","SourceFile","SourceSheet","SourceRow"})
    in
        Master_RACI_Assignments
in RACI_Normalized

// =====================
// Staffing extraction
// =====================
let Staffing_Master =
    let
        files = GetAllFiles(SharePointFolders, SourceExcelFiles),
        wbTables = Table.AddColumn(files, "Tables", each Excel.Workbook([Content], true)),
        expand = Table.ExpandTableColumn(wbTables, "Tables", {"Item","Kind","Data"}, {"SourceSheet","Kind","Data"}),
        only = Table.SelectRows(expand, each [Kind] = "Sheet" or [Kind] = "Table"),
        filtered = Table.SelectRows(only, each @IdentifySheetType([Data]) = "Staffing"),
        transform = Table.AddColumn(filtered, "Normalized", each let t=[Data] in let
            ph = Table.PromoteHeaders(t, [PromoteAllScalars=true]),
            cols = Table.ColumnNames(ph),
            // Standardize column names
            std = Table.TransformColumnNames(ph, each Text.Lower(Text.Replace(_, " ", ""))),
            rename = Table.RenameColumns(std, {
                {"rolename","RoleSourceName"},
                {"role","RoleSourceName"},
                {"fte","FTE"},
                {"consultants","Consultants"},
                {"workload%","Workload%"},
                {"skillproficiency","SkillProficiency"},
                {"coveragerisk","CoverageRisk"},
                {"gapnotes","GapNotes"},
                {"team","Team"},
                {"department","Department"}
            }, MissingField.Ignore),
            // Keep only expected columns (others preserved via SourceSheet/Row)
            keep = Table.SelectColumns(rename, {"RoleSourceName","FTE","Consultants","Workload%","SkillProficiency","CoverageRisk","GapNotes","Team","Department"}, MissingField.UseNull)
            in keep),
        expanded = Table.ExpandTableColumn(transform, "Normalized", {"RoleSourceName","FTE","Consultants","Workload%","SkillProficiency","CoverageRisk","GapNotes","Team","Department"}),
        addSrc = Table.AddColumn(expanded, "SourceFile", each [Name]),
        addRow = Table.AddColumn(addSrc, "SourceRow", each null),
        Master_Staffing = Table.SelectColumns(addRow, {"Team","RoleSourceName","FTE","Consultants","Workload%","SkillProficiency","CoverageRisk","GapNotes","Department","SourceFile","SourceSheet","SourceRow"})
    in
        Master_Staffing
in Staffing_Master

// =====================
// Role Map builder
// =====================
let Role_Map =
    let
        rolesFromRACI = Table.Distinct(Table.SelectColumns(RACI_Normalized, {"RoleSourceName"})),
        rolesFromStaff = Table.Distinct(Table.SelectColumns(Staffing_Master, {"RoleSourceName","Department"})),
        combined = Table.Combine({rolesFromRACI, rolesFromStaff}),
        dedup = Table.Distinct(combined),
        addCanonical = Table.AddColumn(dedup, "RoleCanonical", each Text.Proper(Text.Clean([RoleSourceName]))),
        PreferredDisplayName = Table.AddColumn(addCanonical, "PreferredDisplayName", each [RoleCanonical]),
        Role_Map = Table.SelectColumns(PreferredDisplayName, {"RoleCanonical","PreferredDisplayName","Department"})
    in Role_Map
in Role_Map

// =====================
// Activity normalization & IDs
// =====================
let Master_Activities =
    let
        activities = Table.Distinct(Table.SelectColumns(RACI_Normalized, {"ActivityText","SourceFile","SourceSheet","SourceRow"})),
        // Clean text
        cleaned = Table.TransformColumns(activities, {{"ActivityText", each Text.Trim(Text.Replace(Text.Replace(Text.Lower(_), "", " "), "
", " ")), type text}}),
        // Assign sequential IDs
        addIndex = Table.AddIndexColumn(cleaned, "Index", 1, 1, Int64.Type),
        addID = Table.AddColumn(addIndex, "ActivityID", each "ACT-" & Text.PadStart(Text.From([Index]), 4, "0")),
        removeIdx = Table.RemoveColumns(addID, {"Index"}),
        // Category inference (simple keyword-based)
        addCategory = Table.AddColumn(removeIdx, "Category", each if Text.Contains([ActivityText], "patch") or Text.Contains([ActivityText], "change") then "Patch/Change" else if Text.Contains([ActivityText], "vendor") then "Vendor Mgmt" else if Text.Contains([ActivityText], "compliance") or Text.Contains([ActivityText], "audit") then "Compliance" else "Operations")
    in
        addCategory
in Master_Activities

// =====================
// RACI with ActivityIDs & Role Canonical mapping
// =====================
let Master_RACI_Assignments =
    let
        joinAct = Table.NestedJoin(RACI_Normalized, {"ActivityText"}, Master_Activities, {"ActivityText"}, "Act", JoinKind.LeftOuter),
        expandAct = Table.ExpandTableColumn(joinAct, "Act", {"ActivityID"}),
        joinRole = Table.NestedJoin(expandAct, {"RoleSourceName"}, Role_Map, {"RoleCanonical"}, "RoleMap", JoinKind.LeftOuter),
        addCanonical = Table.AddColumn(expandAct, "RoleCanonical", each if [RoleMap] = null then [RoleSourceName] else [RoleMap][RoleCanonical]{0}),
        final = Table.SelectColumns(addCanonical, {"ActivityID","ActivityText","RoleSourceName","RoleCanonical","RACI","SourceFile","SourceSheet","SourceRow"}),
        addAssignmentID = Table.AddIndexColumn(final, "AssignmentIndex", 1, 1, Int64.Type),
        withID = Table.AddColumn(addAssignmentID, "AssignmentID", each "ASN-" & Text.PadStart(Text.From([AssignmentIndex]), 5, "0")),
        result = Table.RemoveColumns(withID, {"AssignmentIndex"})
    in
        result
in Master_RACI_Assignments

// =====================
// Fuzzy activity dedup proposals
// =====================
let Activity_MergeProposals =
    let
        base = Table.SelectColumns(Master_Activities, {"ActivityID","ActivityText"}),
        // Self-join on text using fuzzy match
        selfJoin = Table.FuzzyJoin(base, base, {"ActivityText"}, {"ActivityText"}, "Dup", [IgnoreCase=true, Threshold=Number.From(FuzzyMatchThreshold)/100.0]),
        expand = Table.ExpandTableColumn(selfJoin, "Dup", {"ActivityID","ActivityText"}, {"Dup_ActivityID","Dup_ActivityText"}),
        // Remove identity matches
        filtered = Table.SelectRows(expand, each [ActivityID] <> [Dup_ActivityID]),
        // Prepare output
        out = Table.TransformColumns(filtered, {{"ActivityText", Text.Upper}, {"Dup_ActivityText", Text.Upper}})
    in out
in Activity_MergeProposals

// =====================
// Staffing Ratio Models, Questionnaire, Dependencies (pass-through)
// =====================
let Staffing_Ratio_Models = Table.FromRows({}, {"Team","DriverName","Unit","AssumptionText","HoursPerUnit","FTEPerUnit","SourceFile","SourceSheet","SourceRow"})
let Questionnaire_Responses = Table.FromRows({}, {"Team","QuestionCategory","QuestionText","ResponseText","SourceFile","SourceSheet","SourceRow"})
let Dependencies_Register = Table.FromRows({}, {"DependencyName","OwningTeam","DependentTeam","Criticality","ImpactIfDelayed","CoordinationHrs","Notes","SourceFile","SourceSheet","SourceRow"})

// =====================
// OrgNodes & OrgEdges
// =====================
let OrgNodes =
    let
        byRole = Table.Group(Master_RACI_Assignments, {"RoleCanonical","Department"}, {{"Count_R", each Table.RowCount(Table.SelectRows(_, each [RACI] = "R")), Int64.Type},{"Count_A", each Table.RowCount(Table.SelectRows(_, each [RACI] = "A")), Int64.Type},{"Count_C", each Table.RowCount(Table.SelectRows(_, each [RACI] = "C")), Int64.Type},{"Count_I", each Table.RowCount(Table.SelectRows(_, each [RACI] = "I")), Int64.Type}}),
        addFTE = Table.NestedJoin(byRole, {"RoleCanonical"}, Staffing_Master, {"RoleSourceName"}, "Staff", JoinKind.LeftOuter),
        expandFTE = Table.ExpandTableColumn(addFTE, "Staff", {"FTE","Team"}, {"TotalFTE","Team"}),
        final = Table.SelectColumns(expandFTE, {"RoleCanonical","Department","Team","TotalFTE","Count_A","Count_R","Count_C","Count_I"})
    in final
in OrgNodes

let OrgEdges =
    let
        // Overlap of activities between roles
        base = Table.SelectColumns(Master_RACI_Assignments, {"ActivityID","RoleCanonical","RACI"}),
        self = Table.NestedJoin(base, {"ActivityID"}, base, {"ActivityID"}, "Join", JoinKind.Inner),
        expanded = Table.ExpandTableColumn(self, "Join", {"RoleCanonical","RACI"}, {"ToRoleCanonical","ToRACI"}),
        // Remove self-links
        filtered = Table.SelectRows(expanded, each [RoleCanonical] <> [ToRoleCanonical]),
        grouped = Table.Group(filtered, {"RoleCanonical","ToRoleCanonical"}, {{"OverlapCount", each Table.RowCount(_), Int64.Type},{"Count_A", each Table.RowCount(Table.SelectRows(_, each [RACI] = "A")), Int64.Type},{"Count_R", each Table.RowCount(Table.SelectRows(_, each [RACI] = "R")), Int64.Type},{"Count_C", each Table.RowCount(Table.SelectRows(_, each [RACI] = "C")), Int64.Type},{"Count_I", each Table.RowCount(Table.SelectRows(_, each [RACI] = "I")), Int64.Type}})
    in grouped
in OrgEdges
